**Taux d'endettement**

In [4]:
from google.colab import drive
import pandas as pd
import gdown

# Montez votre Google Drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:

# ID du fichier extrait du lien Google Drive
file_id = '1_Ym2w09qJ01lY6rWAWvbffOnKcUi9_Fc'

# On reconstruit l'URL au format attendu par gdown
url = f"https://drive.google.com/uc?id={file_id}"

# Chemin de destination pour le fichier téléchargé
output_file = '/tmp/Taux_endettement.csv'

print("Téléchargement du fichier depuis Google Drive...")
# gdown télécharge le fichier dans ton dossier local et affiche une barre de progression
gdown.download(url, output_file, quiet=False)

print("Chargement et filtrage du dataset en cours...")
# 4. On lit le fichier localement avec Pandas (beaucoup plus rapide et stable !)
df = pd.read_csv(output_file)

print("Terminé ! Ton DataFrame 'df_credit' est prêt.")

Téléchargement du fichier depuis Google Drive...

Downloading...
From: https://drive.google.com/uc?id=1_Ym2w09qJ01lY6rWAWvbffOnKcUi9_Fc
To: /tmp/Taux_endettement.csv
100%|██████████| 53.9M/53.9M [00:00<00:00, 99.7MB/s]

Chargement et filtrage du dataset en cours...
Terminé ! Ton DataFrame 'df_credit' est prêt.

In [ ]:
df.head()

In [7]:

import numpy as np

# Créer une copie
df_copy = df.copy()

# Calculer le taux d'endettement
df_copy['tx_endettement'] = round(((df_copy['AMT_ANNUITY']*12) / df_copy['AMT_INCOME_TOTAL']) * 100, 2)

df_copy['tx_endettement']

0         146.37
1         158.66
2         120.00
3         263.88
4         215.96
           ...
307494    209.97
307495    200.02
307496    235.13
307497    141.79
307498    374.23
Name: tx_endettement, Length: 307499, dtype: float64

In [ ]:
# Compte les lignes vides'
nb_manquants = df_copy['tx_endettement'].isnull().sum()
print(f"Nombre de valeurs manquantes : {nb_manquants}")

In [8]:
# Mettre à jour le DataFrame
df = df_copy.copy()

In [13]:
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,AGE,YEARS_EMPLOYED,tx_endettement
0,100002,1,CASH_LOANS,M,N,Y,0,202500.0,406597.5,24700.5,...,WORKING,SECONDARY_/_SECONDARY_SPECIAL,SINGLE_/_NOT_MARRIED,BUSINESS_ENTITY,0.083037,0.262949,0.139376,25.9,1.7,146.37
1,100003,0,CASH_LOANS,F,N,N,0,270000.0,1293502.5,35698.5,...,STATE_SERVANT,HIGHER_EDUCATION,MARRIED,SCHOOL,0.311267,0.622246,NaN,45.9,3.3,158.66
2,100004,0,REVOLVING_LOANS,M,Y,Y,0,67500.0,135000.0,6750.0,...,WORKING,SECONDARY_/_SECONDARY_SPECIAL,SINGLE_/_NOT_MARRIED,GOVERNMENT,NaN,0.555912,0.729567,52.1,0.6,120.00
3,100006,0,CASH_LOANS,F,N,Y,0,135000.0,312682.5,29686.5,...,WORKING,SECONDARY_/_SECONDARY_SPECIAL,CIVIL_MARRIAGE,BUSINESS_ENTITY,NaN,0.650442,NaN,52.0,8.3,263.88
4,100007,0,CASH_LOANS,M,N,Y,0,121500.0,513000.0,21865.5,...,WORKING,SECONDARY_/_SECONDARY_SPECIAL,SINGLE_/_NOT_MARRIED,OTHER,NaN,0.322738,NaN,54.6,8.3,215.96

In [ ]:
df.info()

In [ ]:
import plotly.express as px

fig = px.histogram(df,
                   x='tx_endettement',
                   nbins=50,
                   title="Distribution du Taux d'Endettement",
                   labels={'tx_endettement': "Taux d'Endettement (%)"})
fig.update_xaxes(range=[0, 10]) # Limiter l'axe X jusqu'à 10
fig.show()

In [9]:
from google.colab import drive

drive.mount('/gdrive')

Mounted at /gdrive

In [12]:
import os

chemin_destination = "/gdrive/My Drive/Projet_mydrive/Dataset essentiel/application_train_enrichie.csv"

df.to_csv(chemin_destination, index=False, encoding="utf-8")
print(f"DataFrame exported to: {chemin_destination}")

DataFrame exported to: /gdrive/My Drive/Projet_mydrive/Dataset essentiel/application_train_enrichie.csv

In [14]:
df["credit_score"] = df[["EXT_SOURCE_1", "EXT_SOURCE_2", "EXT_SOURCE_3"]].mean(axis=1)

In [15]:
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,AGE,YEARS_EMPLOYED,tx_endettement,credit_score
0,100002,1,CASH_LOANS,M,N,Y,0,202500.0,406597.5,24700.5,...,SECONDARY_/_SECONDARY_SPECIAL,SINGLE_/_NOT_MARRIED,BUSINESS_ENTITY,0.083037,0.262949,0.139376,25.9,1.7,146.37,0.161787
1,100003,0,CASH_LOANS,F,N,N,0,270000.0,1293502.5,35698.5,...,HIGHER_EDUCATION,MARRIED,SCHOOL,0.311267,0.622246,NaN,45.9,3.3,158.66,0.466757
2,100004,0,REVOLVING_LOANS,M,Y,Y,0,67500.0,135000.0,6750.0,...,SECONDARY_/_SECONDARY_SPECIAL,SINGLE_/_NOT_MARRIED,GOVERNMENT,NaN,0.555912,0.729567,52.1,0.6,120.00,0.642739
3,100006,0,CASH_LOANS,F,N,Y,0,135000.0,312682.5,29686.5,...,SECONDARY_/_SECONDARY_SPECIAL,CIVIL_MARRIAGE,BUSINESS_ENTITY,NaN,0.650442,NaN,52.0,8.3,263.88,0.650442
4,100007,0,CASH_LOANS,M,N,Y,0,121500.0,513000.0,21865.5,...,SECONDARY_/_SECONDARY_SPECIAL,SINGLE_/_NOT_MARRIED,OTHER,NaN,0.322738,NaN,54.6,8.3,215.96,0.322738